//! Raw FFI bindings for libghostty-vt, the terminal emulation library
//! extracted from [Ghostty](https://ghostty.org).
//!
//! The build script builds libghostty-vt from Ghostty's official source
//! tarball with Zig 0.16 and links it statically. `src/bindings.rs` is
//! generated by `tools/gen_bindings.rs` from the pinned headers and is
//! committed, so no bindgen or Clang is needed to build this crate.
//!
//! Adapted from libghostty-vt-sys 0.2.2 (MIT OR Apache-2.0).

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(clippy::all)]
#![allow(rustdoc::all)]

mod bindings;

use std::ops::Deref;

pub use bindings::*;

/// The Ghostty commit this crate builds libghostty-vt from.
pub const GHOSTTY_COMMIT: &str = env!("GHOSTTY_VT_COMMIT");

/// The Ghostty version string reported by the pinned source tarball.
pub const GHOSTTY_VERSION: &str = env!("GHOSTTY_VT_VERSION");

/// Initialize a "sized" FFI object.
#[macro_export]
macro_rules! sized {
    ($ty:ty) => {{
        let mut t = <$ty as ::std::default::Default>::default();
        t.size = ::std::mem::size_of::<$ty>();
        t
    }};
}

impl<S> From<S> for bindings::String
where
    S: Deref<Target = str>,
{
    fn from(value: S) -> Self {
        Self {
            ptr: value.as_ptr(),
            len: value.len(),
        }
    }
}

impl bindings::String {
    /// Borrow the string as raw bytes. A null pointer is treated as an empty
    /// string; the C API does not promise a non-null pointer for zero-length
    /// strings, and `slice::from_raw_parts` requires one even at length zero.
    ///
    /// # Safety
    ///
    /// The caller must uphold that the associated lifetime is valid
    /// with the given context behind the FFI string.
    pub unsafe fn to_bytes<'a>(self) -> &'a [u8] {
        if self.ptr.is_null() {
            return &[];
        }
        // SAFETY: To be upheld by caller
        unsafe { std::slice::from_raw_parts(self.ptr, self.len) }
    }

    /// # Safety
    ///
    /// The caller must uphold that the associated lifetime is valid
    /// with the given context behind the FFI string, and that it contains
    /// valid UTF-8 data.
    pub unsafe fn to_str<'a>(self) -> &'a str {
        // SAFETY: To be upheld by caller
        unsafe { std::str::from_utf8_unchecked(self.to_bytes()) }
    }
}
