//! One module per component.

mod avatar;
mod badge;
mod button;
mod input;
mod menu;
mod nav_stack;
mod progress;
mod scroll_area;
mod select;
mod sidebar;
mod skeleton;
mod spacing;
mod spinner;
mod switch;
mod tabs;
mod tag;
mod textarea;
mod theme_mode_picker;
mod title_bar;
mod typography;

pub use avatar::AvatarStory;
pub use badge::BadgeStory;
pub use button::ButtonStory;
pub use input::InputStory;
pub use menu::MenuStory;
pub use nav_stack::NavStackStory;
pub use progress::ProgressStory;
pub use scroll_area::ScrollAreaStory;
pub use select::SelectStory;
pub use sidebar::SidebarStory;
pub use skeleton::SkeletonStory;
pub use spacing::SpacingStory;
pub use spinner::SpinnerStory;
pub use switch::SwitchStory;
pub use tabs::TabsStory;
pub use tag::TagStory;
pub use textarea::TextareaStory;
pub use theme_mode_picker::ThemeModePickerStory;
pub use title_bar::TitleBarStory;
pub use typography::TypographyStory;
